### PR TITLE
just updated the readme, nothing huge

### PR DESCRIPTION
**Pull request by byronbytes**
To make the repository more popular and highly rated, a clean readme is something that is required. If you like these changes, I'll improve on it a little more.

### CODE REVIEW

**Comment by Hankypoo7** [comment]
thank you for the pull request, looks great :)

**Comment by Snowflake-Coder-H2o** [comment]
@byronbytes Greatly appreciate that! 

Have a great day!

-Snow

**Comment by byronbytes** [comment]
> @byronbytes Greatly appreciate that!
> 
> Have a great day!
> 
> -Snow

Thanks! I found a few more things I could improve so I'll do that quickly as well.

**Comment by Snowflake-Coder-H2o** [comment]
@byronbytes Ok when did u become a collaberator?

**Comment by byronbytes** [comment]
> @byronbytes Ok when did u become a collaberator?

I am not a collaborator, but I'm a contributor. Two completely seperate things, when someone gets an accepted change (like a PR), they become a contributor to the project.

**Comment by Snowflake-Coder-H2o** [comment]
O ok.

**Comment by Snowflake-Coder-H2o** [comment]
Well thanks we really appriate your help.

**Comment by byronbytes** [comment]
> Well thanks we really appriate your help.

No problem!

**Pull request merged**
